declare interface main_keys {
  "Account does not exist!": LanguageConfigType;
  "Account has been frozen!": LanguageConfigType;
  "Account login information is abnormal!": LanguageConfigType;
  "Activity closed": LanguageConfigType;
  "Activity expired": LanguageConfigType;
  "An exception occurred, the game was forcibly dismissed!": LanguageConfigType;
  "An update was detected, please log out and log in again!": LanguageConfigType;
  "Binding failed": LanguageConfigType;
  "Binding succeeded": LanguageConfigType;
  "Buy failed": LanguageConfigType;
  "Buy success": LanguageConfigType;
  "Can't find table.": LanguageConfigType;
  "Chat configuration error!": LanguageConfigType;
  "Configuration abnormal": LanguageConfigType;
  "Configuration error": LanguageConfigType;
  "Daily frequency restriction": LanguageConfigType;
  "Facebook login failed, please enter a valid username and password": LanguageConfigType;
  "Fail": LanguageConfigType;
  "Failed to get bonus": LanguageConfigType;
  "Failed to pull sdk configuration!": LanguageConfigType;
  "Failed to receive reward": LanguageConfigType;
  "Failed to request permission. Go to Settings.": LanguageConfigType;
  "Frequency restriction": LanguageConfigType;
  "Game service discontinued": LanguageConfigType;
  "Get the reward for success": LanguageConfigType;
  "Go": LanguageConfigType;
  "Have you agreed to these permissions?": LanguageConfigType;
  "Insufficient recharge for lucky draw": LanguageConfigType;
  "Invalid Param!": LanguageConfigType;
  "Invalid Phone Number!": LanguageConfigType;
  "Invalid activity": LanguageConfigType;
  "Invalid bonus!": LanguageConfigType;
  "It is forbidden to log in to multiple games with the same account": LanguageConfigType;
  "Loading user game data is abnormal!": LanguageConfigType;
  "Logging in to the game DB is abnormal": LanguageConfigType;
  "Login busy, please try again later!": LanguageConfigType;
  "Login square DB exception!": LanguageConfigType;
  "Login timed out": LanguageConfigType;
  "Lottery status abnormal": LanguageConfigType;
  "Maximum times": LanguageConfigType;
  "Message header exception!": LanguageConfigType;
  "Message processing exception!": LanguageConfigType;
  "Network abnormal, please login again": LanguageConfigType;
  "Network connection error, please contact customer service.-301": LanguageConfigType;
  "Network connection interrupted, please retry.": LanguageConfigType;
  "Network connection timed out": LanguageConfigType;
  "Nickname cannot exceed 15 characters": LanguageConfigType;
  "No": LanguageConfigType;
  "No more attempts": LanguageConfigType;
  "No playing for a long time to exit!": LanguageConfigType;
  "Not enough level": LanguageConfigType;
  "Not enough money to Login game!": LanguageConfigType;
  "Not enough money to use prop!": LanguageConfigType;
  "Not enough top-up": LanguageConfigType;
  "Not sign up the match!": LanguageConfigType;
  "Notice": LanguageConfigType;
  "OTP sending failed, please try again": LanguageConfigType;
  "OTP sent successfully": LanguageConfigType;
  "Offline saving data, try again later!": LanguageConfigType;
  "Offline user kicked out!": LanguageConfigType;
  "Password ERROR!": LanguageConfigType;
  "Perfect information failed": LanguageConfigType;
  "Perfect information success": LanguageConfigType;
  "Play game requires ###, please recharge!": LanguageConfigType;
  "Please contact us, the current game version is wrong": LanguageConfigType;
  "Reconnect": LanguageConfigType;
  "Rewards have been claimed!": LanguageConfigType;
  "Saveing user data exception!": LanguageConfigType;
  "Screenshot complete": LanguageConfigType;
  "Share success": LanguageConfigType;
  "Something went wrong with login, please login again": LanguageConfigType;
  "Success": LanguageConfigType;
  "Success in getting bonus": LanguageConfigType;
  "System Data is abnormal!": LanguageConfigType;
  "Thank you, please win more and good luck!": LanguageConfigType;
  "The Internet link is successful and has returned to the lobby": LanguageConfigType;
  "The configuration is invalid or the product is off the shelf!": LanguageConfigType;
  "The current number of players is full, please try again later": LanguageConfigType;
  "The game is offline, please log in to the game again!": LanguageConfigType;
  "The game is under maintenance, please try again later!": LanguageConfigType;
  "The network connection timed out, please try again. Error code: PHP101": LanguageConfigType;
  "The network is abnormal. Please click Reconnect": LanguageConfigType;
  "The system forcibly kicks it out, if you have any questions, please contact customer service!": LanguageConfigType;
  "The server is being upgraded, please try again later.": LanguageConfigType;
  "There is not enough money": LanguageConfigType;
  "This app requires these permissions to function properly.": LanguageConfigType;
  "This app requires these permissions to work properly": LanguageConfigType;
  "Time has not come": LanguageConfigType;
  "Tips": LanguageConfigType;
  "UNKOWN ERROR": LanguageConfigType;
  "User status abnormal": LanguageConfigType;
  "We have received your feedback, thank you for your valuable comments, we will deal with it as soon as possible, and I wish you a happy game.": LanguageConfigType;
  "Yes": LanguageConfigType;
  "You are not in the lobby": LanguageConfigType;
  "You don't have enough money to bet.Deposit to unlock levels faster.": LanguageConfigType;
  "You have already bought it!": LanguageConfigType;
  "You have too much money, you can go to a high-level table.": LanguageConfigType;
  "You sent too fast": LanguageConfigType;
  "You're back in the lobby because you're not ready.": LanguageConfigType;
  "Your account is logged in elsewhere, if you have any questions, please contact customer service!": LanguageConfigType;
  "Your account is logging in!": LanguageConfigType;
  "activity close": LanguageConfigType;
  "activity finish": LanguageConfigType;
  "config error": LanguageConfigType;
  "data error, please login again": LanguageConfigType;
  "exit": LanguageConfigType;
  "fail": LanguageConfigType;
  "fish config invalid": LanguageConfigType;
  'config invalid': LanguageConfigType;
  "has new plaza version need update": LanguageConfigType;
  "kicked out of the system!": LanguageConfigType;
  "loading user data exception!": LanguageConfigType;
  "login cancel": LanguageConfigType;
  "no config": LanguageConfigType;
  "no server ID": LanguageConfigType;
  "please try again later": LanguageConfigType;
  "recharge not enough": LanguageConfigType;
  "request location permission": LanguageConfigType;
  "room config error": LanguageConfigType;
  "share cancel": LanguageConfigType;
  "update failed": LanguageConfigType;
}

/**多语言key全集，用于提示 */
declare type language_main_keys = {
  [key in keyof main_keys]: LanguageConfigType
}